version: "3.9"
services:    
    graphql:        
        build: .
        ports:
            - "5000:5000"
        links: 
            - mongodb             
    redis_cache:        
        image: redis
        ports:
            - "6379:6379"
