
version: "3.9"
services:    
    graphql:        
        build: .
        ports:
            - "5000:5000"
        links: 
            - mongodb             
    mongodb:        
        image: mongo
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=orderadmin
            - MONGO_INITDB_ROOT_PASSWORD=tu_password
        volumes:
            - mongo-data:/data/db
            # mysql -> /var/lib/mysql
            #postgres -> /var/lib/postgresql/data

volumes:
    mongo-data:
